### ISSUE TITLE
Categories / organization

### ISSUE THREAD

**Issue by tmcw** [documentationjs/styledoc#2]
Right now docs are in source order with no annotations or categories. We'll need those things.

**Comment by davidtheclark** [comment]
How about using `@namespace` and `@memberof` to create categories? 

However, it would be nice if we could build in multiple levels of nesting: Utilities > Layout > Margins > `.margin-15-top` — is there any block tag designed to allow for this?

If we could do this, and have, for example, a `Margins` namespace, one nicety we could build in is the expectation that when you declare a namspace, rules immediately following that comment block *without a line break* are assumed to be members of it.

So instead of

```css
/** @namespace Margins */
/** @memberof Margins */
.margin-top-15 { margin-top: 15; }
/** @memberof Margins */
.margin-bottom-15 { margin-bottom: 15; }
/** @memberof Margins */
.margin-left-15 { margin-left: 15; }
```

we could have

```css
/** @namespace Margins */
.margin-top-15 { margin-top: 15; }
.margin-bottom-15 { margin-bottom: 15; }
.margin-left-15 { margin-left: 15; }
```
